#!/bin/bash
echo "$1"
npm config --global set proxy $1
npm config --global set https-proxy $1
npm config set proxy $1
npm config set https-proxy $1
git config --global http.proxy $1
git config --global https.proxy $1
git config http.proxy $1
git config https.proxy $1
