#!/bin/bash
echo "$1"
if [ ! $1 ]; then
echo 'Please enter the proxy you would like to set.'
echo "Usage: ./cli-proxy '<proxy>'"
echo "Example: ./cli-proxy 'http://172.31.1.4:8080'" 
else
npm config --global set proxy $1
npm config --global set https-proxy $1
npm config set proxy $1
npm config set https-proxy $1
git config --global http.proxy $1
git config --global https.proxy $1
git config http.proxy $1
git config https.proxy $1

npmHTTP="$(npm config get proxy)"
npmHTTPS="$(npm config get https-proxy)"
gitHTTP="$(git config http.proxy)"
gitHTTPS="$(git config https.proxy)"
echo $npmHTTP
if [ $npmHTTP == "$1/" ]; then
echo "NPM user http proxy successfully set to $1"
fi
if [ $npmHTTPS == "$1/" ]; then
echo "NPM user https proxy successfully set to $1"
fi
if [ $gitHTTP == "$1" ]; then
echo "Git user http proxy successfully set to $1"
fi
if [ $gitHTTPS == "$1" ]; then
echo "Git user https proxy successfully set to $1"
fi
fi
